### ISSUE TITLE
Parser fails to detect missing commas.

### ISSUE THREAD

**Issue by derula** [tonioo/sievelib#100]
Example:
```sieve
if address "From" "example.com" header "Subject" "Example" { stop; }
```
Version 1.1.1 finds no problems with this script, even though it's wrong.
To chain tests, `anyof` or `allof` must be used, like so:
```sieve
if allof(address "From" "example.com", header "Subject" "Example") { stop; }
```
If this is already fixed in master, please release a new version.

**Comment by derula** [comment]
Some more research. This will correctly report an error:
```sieve
if allof(address "From" "example.com" header "Subject" "Example") { stop; }
```
But this won't:
```sieve
if allof(anyof(address "From" "example.com") anyof(header "Subject" "Example")) { stop; }
```
It seems like the inner parenthesis make the parser forget about its prior context!?

**Comment by derula** [comment]
First issue seems to be fixed with the following change:
```diff
index 8ef34fa..d7cf89e 100755
--- a/sievelib/parser.py
+++ b/sievelib/parser.py
@@ -235,6 +235,8 @@ class Parser(object):
             cmd = self.__curcommand
             self.__curcommand = self.__curcommand.parent
             if self.__curcommand.get_type() in ["control", "test"]:
+                if self.__curcommand.variable_args_nb:
+                    self.__set_expected("comma", "right_parenthesis")
                 if self.__curcommand.iscomplete():
                     if self.__curcommand.get_type() == "control":
                         break
@@ -242,8 +244,6 @@ class Parser(object):
                 if not self.__curcommand.check_next_arg("test", cmd, add=False):
                     return False
                 if not self.__curcommand.iscomplete():
-                    if self.__curcommand.variable_args_nb:
-                        self.__set_expected("comma", "right_parenthesis")
                     break
 
         return True
```
This doesn't seem to break any other tests.

The change doesn't fix the second problem, however. Seems to be an unrelated issue.

Note: I don't _fully_ understand what the different if branches in my diff above are meant for, so the proposed fix may well be wrong.

**Comment by derula** [comment]
After some debugging, I have no idea where to even start with this one. Main problem seems to be that the parser only _sometimes_ sets `__expected`, seemingly whenever it feels like it, and in completely different parts of the code. I have no idea in which part of the code to set the `__expected` without breaking everything else.

**Comment by tonioo** [comment]
@derula Is it necessary to fix this issue before releasing the new version?

**Comment by derula** [comment]
@tonioo probably not, it seems a bit complex to solve from what I can tell, and all in all it's not that bad b/c managesieve returns an error message if the server doesn't understand something in the script.

**Comment by tonioo** [comment]
@derula Ok then I'll try to make a release this week.

**Comment by derula** [comment]
@tonioo Thanks for the release!

Unfortunately, I found that the parser fails on some more simple examples, such as:

```sieve
if stop;
```

It thinks this is a valid script...

I am now using a new parser using the Lark parser generator for Python, based on this grammar: https://raw.githubusercontent.com/derula/strainer/master/strainer/sieve/parser/sieve.lark

It is between 2 and 10 times slower than your parser, but seems to be better at detecting such fringe cases. So far, it only supports vanilla RFC-5228 with no extensions, but since the grammar is so simple, extending it should be pretty straightforward.

If you're interested, I could extract this parser into a separate Python package, or even replace the parser in SieveLib. It is slower than yours and not a drop-in replacement, so I would like to know how you feel about the idea first.

**Comment by tonioo** [comment]
@derula It could be interesting to include an alternative parser in the package indeed. I'll look at your issue if I have some time this week, it should not be too complicated to fix I guess.

**Comment by tonioo** [comment]
@derula And I was thinking again about your example. Why do you think it should be valid? ``stop`` is an action not a test, I don't think it can be used as a test condition.

**Comment by derula** [comment]
An alternative parser sounds good. I also think it could be interesting to run your tests against my parser. I'll see some time if I can find a good way to do this. I'll send you a PR as soon as I have something usable.

And I suppose you figured it out and deleted the comment asking about it, but yes, `if stop;` should be invalid, and your parser accepted it as legal. At least I _think_ it did, it was one of the last things I tried before switching to my new parser, so it's possible that it was an in-between state where neither parser ran.

**Comment by tonioo** [comment]
@derula Actually the 'stop' issue was pretty easy to fix. Can you check the PR please? I forgot to check if parsed command is actually a test one or not!

**Comment by tonioo** [comment]
@derula I think I fixed all issues you reported. There was indeed some cases where the next expected token was not set properly. Could you check the PR please?

**Comment by derula** [comment]
@tonioo I will try out the PRs soon; code-wise, they look good. Seems like I was pretty close to the solution when I was trying to fix the original issue myself. Thanks!

**Comment by tonioo** [comment]
@derula Have you tested the PRs?

**Comment by derula** [comment]
@tonioo sorry, I've been putting it off, but it's been on my agenda. Let me know if you need an answer soon, then I can test it this weekend.

**Comment by tonioo** [comment]
@derula This weekend is fine, thank you.

**Comment by derula** [comment]
Okay, commented on both PRs.
