### ISSUE TITLE
STARTTLS not recognised

### ISSUE THREAD

**Issue by ReneArnhold** [tonioo/sievelib#33]
I work with a cyrus Server and if I start making a call to sievelib.managesieve.Client.connect with starttls=True i get the "STARTTLS not supported by the server".

With Wireshark i can see the STARTTLS in the capabilities right after the connect on the last line (before the finishing OK).

When I replace 
`for l in capabilities.splitlines()[0:-1]:`
by
`for l in capabilities.splitlines():`
in sievelib/managesieve.py on line 260
the connect is working fine.

**Comment by tonioo** [comment]
Hi, could you paste the capabilities (raw format) sent by Cyrus please ?

**Comment by ReneArnhold** [comment]
"IMPLEMENTATION" "Cyrus timsieved v2.4.8"
"SASL" "PLAIN LOGIN"
"SIEVE" "comparator-i;ascii-numeric fileinto reject vacation imapflags notify include envelope body copy"
"STARTTLS"
OK

**Comment by tonioo** [comment]
Thank you, it should be fixed now.
