### ISSUE TITLE
add_commands documentation

### ISSUE THREAD

**Issue by Dharmik8478** [tonioo/sievelib#44]
Is there any document for adding command?
I have tried to add command but it gives error

```

  File "/opt/pyvirtual/MMC-py_3.4-dj_1.9/lib/python3.4/site-packages/sievelib/factory.py", line 200, in __create_filter
    if action.is_extension:
AttributeError: 'NoneType' object has no attribute 'is_extension'
```

**Comment by tonioo** [comment]
Can you paste an example of the command you're trying to add ?

**Comment by frankf-cgn** [comment]
I think that the reason for your error is, that the code-example in the paragraph "Extending the parser" of `readme.rst` has a small error. 

The code example

**def** MyCommand

must be

**class** MyCommand

**Comment by tonioo** [comment]
@frankf-cgn thank you.
