### ISSUE TITLE
:addresses without a list

### ISSUE THREAD

**Issue by sengaya** [tonioo/sievelib#49]
Not sure if this is covered by the RFC, but with Roundcube I get a sieve script that contains something like this:`:addresses "mail@example.net"`

The parser fails in this case because it should be a list:
```
>>> p.error
'line 12: bad value "mail@example.net" for argument addresses'
```

So it seems to me that :addresses can either be a list of mail addresses or a string containing a mail address.

**Comment by tonioo** [comment]
@sengaya Looks like the RFC allows it (see https://tools.ietf.org/html/rfc5228#section-2.4.2.1). I'll fix this asap.
