### ISSUE TITLE
How to get conditions and actions lists from FiltersSet?

### ISSUE THREAD

**Issue by matteomattei** [tonioo/sievelib#64]
Hello Tonioo,
looking at the documentation I see it is possible to add a new filter passing a name and conditions and actions list

```
from sievelib.factory import FiltersSet
fs = FiltersSet("test")
conditions = [("Sender", ":is", "toto@toto.com"),]
actions = [("fileinto", "Toto"),]
fs.addfilter("rule1", conditions, actions)
fs.tosieve()
```

What I need is to export the two lists (conditions and actions) from FiltersSet, something like this:

```
p = Parser()
p.parse('....sieve rule....')
fs = FiltersSet("test")
fs.from_parser_result(p)
# the following lines is what I would need
conditions = fs.get_conditions()
actions = fs.get_actions()
``` 

Is it possible to add the two above functions or can you help me understanding how to obtain the two arrays?
Thanks!

**Comment by tonioo** [comment]
Hi,
what you ask is not possible at the moment. It would require to scan Command objects in order to retrieve conditions and actions. That's something possible but it requires some work. What is your use case?

**Comment by matteomattei** [comment]
Hi Tonioo, thanks for your answer!
Our use case is basically this: we need to create a web interface where users can read, modify and create their sieve filters. To create sieve filters the function addfilter() should do everything we need but we also need a way to parse the filters already present in Sieve and build the web interface. Ideally the web app should receive a json object with conditions and actions formatted in a similar way (arrays of tuples) so that we can create the proper HTML structure based on it. Once the user has configured/changed the filter, we will send the modfied json back to our web service that will update or create a new filter using the addfilter() or updateFilter().
