### ISSUE TITLE
Lexer returns entire remaining script on unknown token

### ISSUE THREAD

**Issue by derula** [tonioo/sievelib#93]
If there is an unrecognized Token in the middle of the script, the lexer just returns the entire rest of the script in the exception message, and the Parser uses it verbatim. I believe it would make more sense to return everything from the current position up to the next whitespace instead.

**Comment by tonioo** [comment]
@derula Thank you!

**Comment by derula** [comment]
Thanks for accepting my changes, this will make my Sieve GUI a little bit better :)

**Comment by tonioo** [comment]
@derula Sieve GUI? What kind?
